name: Print Software Versions

on: [push] # Запуск при кожному push до репозиторію

jobs:
  # ----------------------------------------------------------------------
  # РОБОТА 1: Рівень Обробки Даних (Node.js/BL)
  # ----------------------------------------------------------------------
  business_logic_versions:
    name: Check BL (Node.js) Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Виведення версії Node.js (мова для BL)
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Використовуємо актуальну LTS версію
          
      - name: Print Node.js Version
        run: |
          echo "--- BUSINESS LOGIC LAYER (BL) ---"
          echo "Node.js (Runtime for Express.js):"
          node -v
          echo "npm (Package Manager):"
          npm -v

  # ----------------------------------------------------------------------
  # РОБОТА 2: Рівень Доступу до Даних (PostgreSQL/AL)
  # ----------------------------------------------------------------------
  database_versions:
    name: Check AL/DB (PostgreSQL) Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Встановлення та виведення версії PostgreSQL
      - name: Install PostgreSQL Client
        # Встановлюємо PostgreSQL клієнт на середовище ubuntu-latest
        run: sudo apt-get update && sudo apt-get install postgresql-client -y

      - name: Print PostgreSQL Version
        run: |
          echo "--- DATA ACCESS LAYER (AL/DB) ---"
          echo "PostgreSQL Client Version (SQL DBMS):"
          psql --version
