name: JS Program Code Convention Check (ESLint)

on: [push]

jobs:
  # ----------------------------------------------------------------------
  # РОБОТА 1: Перевірка чистого коду (Expected PASS)
  # ----------------------------------------------------------------------
  lint_clean_module:
    name: Check ProgramCode.js (Expected PASS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          
      - name: Install ESLint Dependencies
        run: |
          npm init -y
          npm install --save-dev eslint@8 eslint-config-airbnb-base eslint-plugin-import
          
      - name: Create ESLint Configuration
        run: |
          cat > .eslintrc.json << 'EOF'
          {
            "extends": ["airbnb-base"],
            "env": {
              "node": true,
              "es2021": true
            },
            "parserOptions": {
              "ecmaVersion": 2021,
              "sourceType": "module"
            },
            "rules": {
              "no-console": "off",
              "semi": ["error", "always"],
              "quotes": ["error", "single"],
              "no-var": "error"
            }
          }
          EOF
          
      - name: Run Code Convention Check (Original File)
        run: npx eslint ProgramCode.js


  # ----------------------------------------------------------------------
  # РОБОТА 2: Перевірка навмисно порушеного коду (Expected FAIL)
  # ----------------------------------------------------------------------
  lint_modified_module:
    name: Check ProgramCodeModified.js (Expected FAIL)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint Dependencies
        run: |
          npm init -y
          npm install --save-dev eslint@8 eslint-config-airbnb-base eslint-plugin-import
          
      - name: Create ESLint Configuration
        run: |
          cat > .eslintrc.json << 'EOF'
          {
            "extends": ["airbnb-base"],
            "env": {
              "node": true,
              "es2021": true
            },
            "parserOptions": {
              "ecmaVersion": 2021,
              "sourceType": "module"
            },
            "rules": {
              "no-console": "off",
              "semi": ["error", "always"],
              "quotes": ["error", "single"],
              "no-var": "error"
            }
          }
          EOF

      - name: Run Modified Code Check (Expected FAIL)
        run: npx eslint ProgramCodeModified.js
        continue-on-error: true
