name: JS Program Code Convention Check (ESLint)

on: [push] # Запуск при кожному push

jobs:
  # ----------------------------------------------------------------------
  # РОБОТА 1: Перевірка чистого коду (Expected PASS)
  # ----------------------------------------------------------------------
  lint_clean_module:
    name: Check ProgramCode.js (Expected PASS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          
      - name: Install ESLint and Dependencies
        # Встановлюємо залежності та створюємо package.json для обходу помилок ESLint
        run: |
          npm init -y # Створюємо package.json
          npm install --save-dev eslint eslint-config-airbnb-base eslint-plugin-import --legacy-peer-deps
          # Додаємо "type": "module" до package.json, щоб усунути попередження
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json')); pkg.type = 'module'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Create ESLint Configuration (eslint.config.js)
        # Правильна конфігурація з розгортанням конфігурації airbnb
        run: |
          echo "import airbnbConfig from 'eslint-config-airbnb-base';" > eslint.config.js
          echo "import globals from 'globals';" >> eslint.config.js
          echo "" >> eslint.config.js
          echo "const airbnb = airbnbConfig;" >> eslint.config.js
          echo "export default [" >> eslint.config.js
          echo "  ...airbnb," >> eslint.config.js
          echo "  {" >> eslint.config.js
          echo "    files: ['**/*.js']," >> eslint.config.js
          echo "    languageOptions: {" >> eslint.config.js
          echo "      globals: globals.node," >> eslint.config.js
          echo "      sourceType: 'module'," >> eslint.config.js
          echo "      ecmaVersion: 2021," >> eslint.config.js
          echo "    }," >> eslint.config.js
          echo "    rules: {" >> eslint.config.js
          echo "      'no-console': 'off'," >> eslint.config.js
          echo "      'semi': ['error', 'always']," >> eslint.config.js
          echo "    }," >> eslint.config.js
          echo "  }," >> eslint.config.js
          echo "];" >> eslint.config.js
          
      - name: Run Code Convention Check (Original File)
        run: ./node_modules/.bin/eslint ProgramCode.js


  # ----------------------------------------------------------------------
  # РОБОТА 2: Перевірка навмисно порушеного коду (Expected FAIL)
  # ----------------------------------------------------------------------
  lint_modified_module:
    name: Check ProgramCodeModified.js (Expected FAIL)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint and Configuration
        # Повторюємо встановлення та конфігурацію для цієї окремої Job
        run: |
          npm init -y
          npm install --save-dev eslint eslint-config-airbnb-base eslint-plugin-import --legacy-peer-deps
          node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json')); pkg.type = 'module'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          
      - name: Create ESLint Configuration
        run: |
          echo "import airbnbConfig from 'eslint-config-airbnb-base';" > eslint.config.js
          echo "import globals from 'globals';" >> eslint.config.js
          echo "" >> eslint.config.js
          echo "const airbnb = airbnbConfig;" >> eslint.config.js
          echo "export default [" >> eslint.config.js
          echo "  ...airbnb," >> eslint.config.js
          echo "  {" >> eslint.config.js
          echo "    files: ['**/*.js']," >> eslint.config.js
          echo "    languageOptions: {" >> eslint.config.js
          echo "      globals: globals.node," >> eslint.config.js
          echo "      sourceType: 'module'," >> eslint.config.js
          echo "      ecmaVersion: 2021," >> eslint.config.js
          echo "    }," >> eslint.config.js
          echo "    rules: {" >> eslint.config.js
          echo "      'no-console': 'off'," >> eslint.config.js
          echo "      'semi': ['error', 'always']," >> eslint.config.js
          echo "    }," >> eslint.config.js
          echo "  }," >> eslint.config.js
          echo "];" >> eslint.config.js

      - name: Run Modified Code Check (Expected FAIL)
        run: ./node_modules/.bin/eslint ProgramCodeModified.js
        continue-on-error: true
